# Generated by Django 5.1.5 on 2025-02-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FloatingData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state_code", models.IntegerField()),
                ("district_code", models.IntegerField()),
                ("region_name", models.CharField(max_length=255)),
                ("enumeration_code", models.CharField(max_length=10)),
                ("floating_pop", models.IntegerField()),
                ("subdistrict_code", models.IntegerField()),
                ("village_code", models.IntegerField()),
            ],
            options={
                "db_table": "floating_data",
            },
        ),
        migrations.CreateModel(
            name="PopulationData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state_code", models.IntegerField()),
                ("district_code", models.IntegerField()),
                ("subdistrict_code", models.IntegerField()),
                ("village_code", models.IntegerField()),
                ("region_name", models.CharField(max_length=255)),
                ("population_2011", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "population_data",
            },
        ),
        migrations.CreateModel(
            name="PopulationDataYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state_code", models.IntegerField()),
                ("district_code", models.IntegerField()),
                ("subdistrict_code", models.IntegerField()),
                ("region_name", models.CharField(max_length=255)),
                ("population_1951", models.IntegerField()),
                ("population_1961", models.IntegerField()),
                ("population_1971", models.IntegerField()),
                ("population_1981", models.IntegerField()),
                ("population_1991", models.IntegerField()),
                ("population_2001", models.IntegerField()),
                ("population_2011", models.IntegerField()),
            ],
            options={
                "db_table": "population_data_year",
            },
        ),
    ]
