# Generated by Django 5.1.6 on 2025-02-10 06:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SpatialVector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(srid=4326),
                ),
                (
                    "shapefile",
                    models.FileField(
                        help_text="Upload a ZIP file containing the Shapefile (.shp, .shx, .dbf, .prj)",
                        upload_to="shapefiles/",
                    ),
                ),
            ],
        ),
    ]
