# Generated by Django 5.1.6 on 2025-02-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapping", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="spatialvector",
            name="attributes",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="spatialvector",
            name="shapefile",
            field=models.FileField(upload_to="shapefiles/"),
        ),
    ]
