# Generated by Django 5.1.6 on 2025-02-16 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state_id", models.IntegerField()),
                ("state_name", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("district_id", models.IntegerField()),
                ("district_name", models.CharField(max_length=30)),
                (
                    "state_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stp.state"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sub_district",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subdistrict_id", models.IntegerField()),
                ("subdistrict_name", models.CharField(max_length=30)),
                (
                    "district_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stp.district"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Villages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("village_id", models.IntegerField()),
                ("village_name", models.CharField(max_length=30)),
                ("sewage_gap", models.DecimalField(decimal_places=10, max_digits=20)),
                (
                    "mean_temperature",
                    models.DecimalField(decimal_places=10, max_digits=20),
                ),
                (
                    "mean_rainfall",
                    models.DecimalField(decimal_places=10, max_digits=20),
                ),
                ("number_of_tourists", models.IntegerField()),
                (
                    "water_quality_index",
                    models.DecimalField(decimal_places=10, max_digits=20),
                ),
                ("number_of_asi_sites", models.IntegerField()),
                (
                    "gdp_at_current_prices",
                    models.DecimalField(decimal_places=10, max_digits=20),
                ),
                (
                    "subdistrict_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stp.sub_district",
                    ),
                ),
            ],
        ),
    ]
